{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.0.jar",
          "url": "room-compiler-processing-2.4.0.jar",
          "size": 824423,
          "sha512": "5a7aec4cae28008b5a169ee7c9cd99fb0c0c7df853ead2aab951019d8a097d44d5ee7664c53a36109e387b7ed1553b92c105ceeff34c8ab87ca614d994c9dbac",
          "sha256": "ab33019ac424139b20c46c005fb0cd08cde8607457b8df26c78d7927f4b73f3b",
          "sha1": "bd432043d9df9b7aa1c9dcb152865b837dba938f",
          "md5": "d52d5328b784319bc97cb45b0ae93a8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.0.jar",
          "url": "room-compiler-processing-2.4.0.jar",
          "size": 824423,
          "sha512": "5a7aec4cae28008b5a169ee7c9cd99fb0c0c7df853ead2aab951019d8a097d44d5ee7664c53a36109e387b7ed1553b92c105ceeff34c8ab87ca614d994c9dbac",
          "sha256": "ab33019ac424139b20c46c005fb0cd08cde8607457b8df26c78d7927f4b73f3b",
          "sha1": "bd432043d9df9b7aa1c9dcb152865b837dba938f",
          "md5": "d52d5328b784319bc97cb45b0ae93a8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.4.0-sources.jar",
          "url": "room-compiler-processing-2.4.0-sources.jar",
          "size": 176771,
          "sha512": "5d847431cd1a321899e72e301de7c29e8c45c64c016acd055387031b4fbc5783bbc4a185a02bdb98fedf3af1d419788585ea466edc73290f172b360a388ab92f",
          "sha256": "84b079950af61f48659c37190fb1d003175432ea6b8a9573d53f765a1159e1f1",
          "sha1": "58de4616dfa577457f389705dd9ddd261958032e",
          "md5": "e3b13d19cc9119c97309a34111012d95"
        }
      ]
    }
  ]
}
