{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.4.0.aar",
          "url": "room-runtime-2.4.0.aar",
          "size": 137138,
          "sha512": "ccfc5b3cf4ccc06a1d91e373025a2058442c529fd6b8336f65fa370829812d8a4fd0ce9cc70cb8c5b9e88a469685ac69f221be35ddce219e929cb2c4060dc6cf",
          "sha256": "6fbe3d6d1214a260cd76d842c9bbcee508f13928a86bb83f3fa60286a2c90860",
          "sha1": "e9ded7d49015f96b619cb8c951e8f1a840ca0532",
          "md5": "30106e3770637a92f6125d00c4b485db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.4.0.aar",
          "url": "room-runtime-2.4.0.aar",
          "size": 137138,
          "sha512": "ccfc5b3cf4ccc06a1d91e373025a2058442c529fd6b8336f65fa370829812d8a4fd0ce9cc70cb8c5b9e88a469685ac69f221be35ddce219e929cb2c4060dc6cf",
          "sha256": "6fbe3d6d1214a260cd76d842c9bbcee508f13928a86bb83f3fa60286a2c90860",
          "sha1": "e9ded7d49015f96b619cb8c951e8f1a840ca0532",
          "md5": "30106e3770637a92f6125d00c4b485db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.4.0-sources.jar",
          "url": "room-runtime-2.4.0-sources.jar",
          "size": 96342,
          "sha512": "8fe6c4e03dfb4804c04cab6632f95a1afbb60f95bf4843f4214741fbd8bc20a7e8872ca3f15cfb8f4a09b495f7f4e2d5eafff65a1e1699a4ceaf992d8bb5bec6",
          "sha256": "4cdaf39a13e0a2b286a926bc05254b504d94fa44974117e337a0c7941fe463f9",
          "sha1": "d4f62905288562601135a254e4ebeab83c3ac648",
          "md5": "09e277f13b4ea843a24a5fe8e5a3a4a7"
        }
      ]
    }
  ]
}
