{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.4.0-rc01.aar",
          "url": "navigation-fragment-2.4.0-rc01.aar",
          "size": 57539,
          "sha512": "e91cd6651f875a7d92e2356506b55978d1ac2e9a09c15a732151780e2e1fef9b81f838f9b9879f87e990eeb302cf2e7c5d1386d7ab4fe66d60ee981fa587b750",
          "sha256": "0ed3d412782847f734a0b1d846ed8a4134cf837d55f8b4cc6947702c1cdafa3b",
          "sha1": "1dcb92ffc8d3b6e45a87bfebbab83b6b03b8ce03",
          "md5": "3b0e0281574da5aff54a75b1da207324"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.4.0-rc01.aar",
          "url": "navigation-fragment-2.4.0-rc01.aar",
          "size": 57539,
          "sha512": "e91cd6651f875a7d92e2356506b55978d1ac2e9a09c15a732151780e2e1fef9b81f838f9b9879f87e990eeb302cf2e7c5d1386d7ab4fe66d60ee981fa587b750",
          "sha256": "0ed3d412782847f734a0b1d846ed8a4134cf837d55f8b4cc6947702c1cdafa3b",
          "sha1": "1dcb92ffc8d3b6e45a87bfebbab83b6b03b8ce03",
          "md5": "3b0e0281574da5aff54a75b1da207324"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-2.4.0-rc01-sources.jar",
          "url": "navigation-fragment-2.4.0-rc01-sources.jar",
          "size": 23709,
          "sha512": "c33afadc26917362d4424126e4558a101fc7e8e624580d858e8a573a94a8d49639ab9100beba810e61d951458789435138a75575852d71a73b3ed8354f9b656c",
          "sha256": "045b4a4fb495ac82fb6cd7abe753fbe53d1754d4abfb4be9352a4a8651592522",
          "sha1": "83eb9ba36f36f08cb87db7db2cf0cf37523aad1b",
          "md5": "3cec0f7679486739596bd04b968f43a7"
        }
      ]
    }
  ]
}
