{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.0-rc01.aar",
          "url": "window-1.0.0-rc01.aar",
          "size": 161003,
          "sha512": "78dc3664b7083de2941dc9df59d9d2d5504b01bfdb0df02d88bb845ea43d6f8bd94376689dab044f865c1984112b3d14aa99ca99621266e02e6c79e550a511e0",
          "sha256": "9b7242511a09ccacccb4a083393d9debb8f7ab3e4b1b66f75c686feef8c14150",
          "sha1": "e95ebb458d5d36c33aca3db26220bb1230092b19",
          "md5": "6bdcd8e8dff4d0d9708f48036811dbfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.0-rc01.aar",
          "url": "window-1.0.0-rc01.aar",
          "size": 161003,
          "sha512": "78dc3664b7083de2941dc9df59d9d2d5504b01bfdb0df02d88bb845ea43d6f8bd94376689dab044f865c1984112b3d14aa99ca99621266e02e6c79e550a511e0",
          "sha256": "9b7242511a09ccacccb4a083393d9debb8f7ab3e4b1b66f75c686feef8c14150",
          "sha1": "e95ebb458d5d36c33aca3db26220bb1230092b19",
          "md5": "6bdcd8e8dff4d0d9708f48036811dbfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "window-1.0.0-rc01-sources.jar",
          "url": "window-1.0.0-rc01-sources.jar",
          "size": 66779,
          "sha512": "e67bb5d681324aebd97b8162ca16139bcbc1e88e8360c50ef029cb87c4c57d5ba1be9b8699d13c20a0587a80ea6f8f6be78d5aea4b4fd5faee47ef0a27c407cd",
          "sha256": "9c68ea6f87898cdb1bd0ddf6ed7f20715f7fd54727749ef00f3e73b75f5ea66a",
          "sha1": "5a4929a59cb71e7c184259f2e088e1be36375f94",
          "md5": "ae4092f9fbf890981c3276936c5797d8"
        }
      ]
    }
  ]
}
