{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.0-rc01.aar",
          "url": "navigation-ui-2.4.0-rc01.aar",
          "size": 95064,
          "sha512": "bdc361f384a60fab56a1186f3f64bf5c993378fe8c0c90f6ab98845e7c6d78914764977cea698d4f9b00a2b25dff12d90994dfc47323ff8bc67db5c9e1b38b26",
          "sha256": "6686c50258eb949e2545ed4fd8372a66fd2b2349dd69e00ed2ad27664e346f41",
          "sha1": "2e3576d411b426dd8211b8cba38607d168651ce7",
          "md5": "3056f744f4362a691a2ab220a29fb7af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.0-rc01.aar",
          "url": "navigation-ui-2.4.0-rc01.aar",
          "size": 95064,
          "sha512": "bdc361f384a60fab56a1186f3f64bf5c993378fe8c0c90f6ab98845e7c6d78914764977cea698d4f9b00a2b25dff12d90994dfc47323ff8bc67db5c9e1b38b26",
          "sha256": "6686c50258eb949e2545ed4fd8372a66fd2b2349dd69e00ed2ad27664e346f41",
          "sha1": "2e3576d411b426dd8211b8cba38607d168651ce7",
          "md5": "3056f744f4362a691a2ab220a29fb7af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.4.0-rc01-sources.jar",
          "url": "navigation-ui-2.4.0-rc01-sources.jar",
          "size": 20800,
          "sha512": "6a04f004d3ace555ba21dcfec22dc62dda488516ecf19e2d8e8d4a19f8e8ed43bfbd0857a2a97d4b3221bcf36c38e024ce56630de4debe75bdc531acf2808a0c",
          "sha256": "cf467e3bde7f9bb5b09e3405aa27b4cca09962b3940e65442b3d9075158f4752",
          "sha1": "89d1adbee4f51f0894d7bbd09355ea2dadd307c1",
          "md5": "6ea3eb2e7c238ce796a91a66fa3948bb"
        }
      ]
    }
  ]
}
