{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.0-rc01.aar",
          "url": "navigation-runtime-2.4.0-rc01.aar",
          "size": 117204,
          "sha512": "a6dd5ef4cf2a7a0290cf53fc16b04f8ef4e8b2ce2e03da99844db448d088d2d13b1d649113efe2fac974021ef1b01c37749b02e3bb7b1a1769edda9d3ba95a24",
          "sha256": "b14b3e088b6a0edb23a6c875fe31ab0250b7f26ffaedc699267b1c5bb0a3f128",
          "sha1": "48dc824c8e240f954866d10b530950c16db47e8d",
          "md5": "55f497b55ce75ddfcb56f241a2267a6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.0-rc01.aar",
          "url": "navigation-runtime-2.4.0-rc01.aar",
          "size": 117204,
          "sha512": "a6dd5ef4cf2a7a0290cf53fc16b04f8ef4e8b2ce2e03da99844db448d088d2d13b1d649113efe2fac974021ef1b01c37749b02e3bb7b1a1769edda9d3ba95a24",
          "sha256": "b14b3e088b6a0edb23a6c875fe31ab0250b7f26ffaedc699267b1c5bb0a3f128",
          "sha1": "48dc824c8e240f954866d10b530950c16db47e8d",
          "md5": "55f497b55ce75ddfcb56f241a2267a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.4.0-rc01-sources.jar",
          "url": "navigation-runtime-2.4.0-rc01-sources.jar",
          "size": 47025,
          "sha512": "b32b2aaa18c870b8d0e402707389eff4359af21d2e562ccbc36cd64132898f87678929e245f876c0a945851c7eefbccc26d73e2935b0d3e68db4cc7cad6e6fd2",
          "sha256": "4ae42be6c8b2b62360d6e3799e2696cb899816471036ba33733213fd8050cdf4",
          "sha1": "2f2bed27eb4e857fb5cc5446a288654e775c3486",
          "md5": "98eb636b94adf191ac9c4ffdb5eb5971"
        }
      ]
    }
  ]
}
