{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "room-compiler-2.4.0.jar",
          "url": "room-compiler-2.4.0.jar",
          "size": 3735501,
          "sha512": "5a57d9b76fa25eb6d510b6af9d204b50a06528c9d8f29062d05d285be0383137ec72971591e6d084c3659128215fa47f82ea2d20c3636664ac62fb455a6b2eae",
          "sha256": "47eb390bbf2772afa8c7154e4bf359c0843a05c8e26538115aee0ef9702f176d",
          "sha1": "921c834d1a8f2069bcd82aa594da5182ef9bfe50",
          "md5": "681b3de2bb88d1b9e90116d61f722f72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.36.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.4.0.jar",
          "url": "room-compiler-2.4.0.jar",
          "size": 3735501,
          "sha512": "5a57d9b76fa25eb6d510b6af9d204b50a06528c9d8f29062d05d285be0383137ec72971591e6d084c3659128215fa47f82ea2d20c3636664ac62fb455a6b2eae",
          "sha256": "47eb390bbf2772afa8c7154e4bf359c0843a05c8e26538115aee0ef9702f176d",
          "sha1": "921c834d1a8f2069bcd82aa594da5182ef9bfe50",
          "md5": "681b3de2bb88d1b9e90116d61f722f72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.4.0-sources.jar",
          "url": "room-compiler-2.4.0-sources.jar",
          "size": 445016,
          "sha512": "51dbf2a07e41d73f66f8387fc5b42828a88326fa2321460b72f32f55478bea3903e7a66fad46dda20124ff12a7992095eed75e77e26d3fefb36742b96427028a",
          "sha256": "4410e9764bc1a7d19e595d6ffb5a6a16022dd63a157f9d867b47df68ec28b663",
          "sha1": "525a8400b368559785745afc2bdfe109c1f8e9ab",
          "md5": "ac595141136e546826ce10e853ea0185"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.4.0.jar",
          "url": "room-compiler-2.4.0.jar",
          "size": 3735501,
          "sha512": "5a57d9b76fa25eb6d510b6af9d204b50a06528c9d8f29062d05d285be0383137ec72971591e6d084c3659128215fa47f82ea2d20c3636664ac62fb455a6b2eae",
          "sha256": "47eb390bbf2772afa8c7154e4bf359c0843a05c8e26538115aee0ef9702f176d",
          "sha1": "921c834d1a8f2069bcd82aa594da5182ef9bfe50",
          "md5": "681b3de2bb88d1b9e90116d61f722f72"
        }
      ]
    }
  ]
}
