{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slidingpanelayout",
    "module": "slidingpanelayout",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slidingpanelayout-1.2.0-rc01.aar",
          "url": "slidingpanelayout-1.2.0-rc01.aar",
          "size": 38003,
          "sha512": "2e78eba17818102187653f70a266dcc555a7fb2b4477799797f3f315bb1536d2ba7e4ce34f54c43f5b7f13cea4e26cf2e6cf2bc1c9714facd6869ad075646aaa",
          "sha256": "b34d9b0db91a876455c3f9f020ddc9d57cf8a65b7f0a724e699282406d55642a",
          "sha1": "2c5ab1a8730b7d0d2627363483937d392e289ab5",
          "md5": "cfebc01125ee741b9f919b770544dd52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "slidingpanelayout-1.2.0-rc01.aar",
          "url": "slidingpanelayout-1.2.0-rc01.aar",
          "size": 38003,
          "sha512": "2e78eba17818102187653f70a266dcc555a7fb2b4477799797f3f315bb1536d2ba7e4ce34f54c43f5b7f13cea4e26cf2e6cf2bc1c9714facd6869ad075646aaa",
          "sha256": "b34d9b0db91a876455c3f9f020ddc9d57cf8a65b7f0a724e699282406d55642a",
          "sha1": "2c5ab1a8730b7d0d2627363483937d392e289ab5",
          "md5": "cfebc01125ee741b9f919b770544dd52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slidingpanelayout-1.2.0-rc01-sources.jar",
          "url": "slidingpanelayout-1.2.0-rc01-sources.jar",
          "size": 17923,
          "sha512": "25e24c0b73d3647dab35fa8512ca2d515820975024ef27d79a5a4e2607b6aebd8fc00ed24b700de71d744e0867766d8e06f6b3172cb40b3e5ca3a61755735157",
          "sha256": "2c231f1699eaba44f6ff27b4906df51e5df22ee169569f05891e34fe2b97e50e",
          "sha1": "6cdf3fd538b995c58d602da7114a92fdeeff92ac",
          "md5": "0cc0b0cb28415ea6a0d975eb7c8e2442"
        }
      ]
    }
  ]
}
